### ISSUE TITLE
bug in running resnet50rnn

### ISSUE THREAD

**Issue by chanajianyu** [jiyanggao/Video-Person-ReID#13]
Traceback (most recent call last):
  File "main_video_person_reid.py", line 290, in <module>
    main()
  File "main_video_person_reid.py", line 158, in main
    model = nn.DataParallel(model).cuda()
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/wjw/opt/anaconda3/envs/pytorch3/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError

**Comment by chanajianyu** [comment]
the platform is :
     linux 16.04o
     cuda 8.0

**Comment by chanajianyu** [comment]
I have solved it!

**Comment by swg209** [comment]
@chanajianyu  Hi，I run the resnetrnn model with torch 0.4, torchvision 0.2 , but got this error:  
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7102 but linked against 7301

I am using CUDA 9.0
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

what can be done to solve the problem? Thx

**Comment by Linranran** [comment]
@chanajianyu hi 四月，你是怎么解决这个问题的？我也遇到了

**Comment by Linranran** [comment]
https://github.com/pytorch/pytorch/issues/5667
