### ISSUE TITLE
training

### ISSUE THREAD

**Issue by jjy201314** [jiyanggao/Video-Person-ReID#3]
when i run the code ,i have the problem:
Traceback (most recent call last):
  File "main_video_person_reid.py", line 293, in <module>
    main()
  File "main_video_person_reid.py", line 118, in main
    pin_memory=pin_memory, drop_last=True,
  File "/home/jiayan/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 437, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/jiayan/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 124, in __init__
    .format(sampler))
ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=<samplers.RandomIdentitySampler object at 0x7fb136700f60>

i don't know where is the prolem. thank you very much! @jiyanggao

**Comment by lqili** [comment]
I had same problem,could you tell me how to solve it?
